### ISSUE TITLE
获取项目文件失败

### ISSUE THREAD

**Issue by sk95120** [renhui/Thinking-in-AV#1]
zip下载和git下载失败。也怨我这网络。
大佬能发个网盘地址吗。

**Comment by renhui** [comment]
链接: https://pan.baidu.com/s/1_JSWwF02dob3rVf3UIF7CQ 提取码: bgbe 复制这段内容后打开百度网盘手机App，操作更方便哦 @sk95120

**Comment by sk95120** [comment]
Thanks
